spring.application.name=finsight-backend
server.port=8080
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

spring.datasource.url=jdbc:postgresql://localhost:5432/db_finsight
spring.datasource.username=postgres
spring.datasource.password=adm

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
